#!/usr/bin/env node

/**
 * Email Preview Generator
 * Compiles MJML, opens in browser, and takes screenshots for review
 * 
 * Usage:
 *   node scripts/preview.js              # Preview all emails
 *   node scripts/preview.js --email day1 # Preview specific email
 */

import dotenv from 'dotenv';
import { Command } from 'commander';
import path from 'path';
import fs from 'fs';
import { fileURLToPath } from 'url';

import { buildEmail } from '../src/services/mjml-compiler.js';
import { loadLinkMap, replaceLinks } from '../src/utils/link-replacer.js';
import { applyCompliance } from '../src/utils/content-compliance.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Load environment variables
dotenv.config({ path: path.join(__dirname, '../.env') });

// Email content configurations
import { emailConfigs } from '../src/emails-config.js';

/**
 * Wrap HTML in a complete document for browser preview
 */
function wrapForBrowser(html) {
  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Email Preview</title>
  <style>
    body { 
      margin: 0; 
      padding: 20px; 
      background-color: #f0f0f0;
      font-family: Arial, sans-serif;
    }
    .preview-container {
      max-width: 600px;
      margin: 0 auto;
      background: white;
      box-shadow: 0 2px 10px rgba(0,0,0,0.1);
    }
    .email-content {
      border: 1px solid #ddd;
    }
    .preview-header {
      background: #2C3E50;
      color: white;
      padding: 15px 20px;
      text-align: center;
    }
    .preview-footer {
      background: #f5f5f5;
      padding: 15px;
      text-align: center;
      font-size: 12px;
      color: #666;
    }
    .mobile-toggle {
      position: fixed;
      top: 20px;
      right: 20px;
      background: #2C3E50;
      color: white;
      padding: 10px 20px;
      border-radius: 4px;
      cursor: pointer;
      z-index: 1000;
    }
  </style>
</head>
<body>
  <div class="preview-container">
    <div class="preview-header">
      <strong>📧 Email Preview</strong> - <span id="email-name"></span>
    </div>
    <div class="email-content">
      ${html}
    </div>
    <div class="preview-footer">
      <p>Generated by Cameron Estate Email Factory</p>
      <p>To test: Send this HTML to your email or use Litmus/Email on Acid</p>
    </div>
  </div>
  
  <script>
    // Toggle mobile/desktop view
    let isMobile = false;
    document.querySelector('.preview-container').style.maxWidth = '600px';
    
    document.addEventListener('keydown', (e) => {
      if (e.key === 'm' || e.key === 'M') {
        isMobile = !isMobile;
        document.querySelector('.preview-container').style.maxWidth = isMobile ? '375px' : '600px';
        console.log('Mobile view:', isMobile);
      }
    });
  </script>
</body>
</html>
  `;
}

/**
 * Process a single email for preview
 */
async function processEmail(emailId) {
  const config = emailConfigs[emailId];
  
  if (!config) {
    console.error(`Email config not found: ${emailId}`);
    return null;
  }
  
  console.log(`\n📧 Processing: ${config.name}`);
  
  try {
    // Load link map
    const linkMap = loadLinkMap();
    console.log(`   ✓ Loaded ${Object.keys(linkMap).length} links`);
    
    // Build email
      
      // Dynamic import to get generateGallery from build.js
      const { generateGallery } = await import('../src/build.js');
      const galleryMJML = generateGallery(config.gallery || { layout: 'none' });

      // Build email
      const buildResult = buildEmail({
        openingContent: config.openingContent ? replaceLinks(applyCompliance(config.openingContent).content, linkMap).content : '',
        content: config.content ? replaceLinks(applyCompliance(config.content).content, linkMap).content : '',
        gallery: galleryMJML,
        variables: {
          previewText: config.previewText,
          first_name: 'Guest' // Default for preview
        }
      });
    
    if (!buildResult.success) {
      throw new Error(`MJML compilation failed: ${buildResult.error}`);
    }
    console.log(`   ✓ MJML compiled to HTML`);
    
    // Create preview HTML
    const previewHtml = wrapForBrowser(buildResult.html);
    
    // Save preview HTML
    const previewDir = path.join(__dirname, '../output/preview');
    if (!fs.existsSync(previewDir)) {
      fs.mkdirSync(previewDir, { recursive: true });
    }
    
    const previewPath = path.join(previewDir, `${emailId}-preview.html`);
    fs.writeFileSync(previewPath, previewHtml);
    console.log(`   ✓ Saved preview: ${previewPath}`);
    
    // Save raw HTML
    const rawHtmlPath = path.join(previewDir, `${emailId}.html`);
    fs.writeFileSync(rawHtmlPath, buildResult.html);
    console.log(`   ✓ Saved raw HTML: ${rawHtmlPath}`);
    
    // Create metadata file
    const metadata = {
      name: config.name,
      subject: config.subject,
      previewText: config.previewText,
      images: config.images,
      generated: new Date().toISOString(),
      files: {
        preview: `${emailId}-preview.html`,
        html: `${emailId}.html`
      }
    };
    
    const metadataPath = path.join(previewDir, `${emailId}-meta.json`);
    fs.writeFileSync(metadataPath, JSON.stringify(metadata, null, 2));
    
    return {
      success: true,
      name: config.name,
      subject: config.subject,
      previewPath,
      rawHtmlPath
    };
    
  } catch (error) {
    console.error(`   ✗ Error: ${error.message}`);
    return {
      success: false,
      name: config.name,
      error: error.message
    };
  }
}

/**
 * Generate approval HTML with all previews
 */
async function generateApprovalPage(results) {
  const successResults = results.filter(r => r.success);
  
  const approvalHtml = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Cameron Estate Email Approval</title>
  <style>
    body { 
      margin: 0; 
      padding: 40px; 
      background: #f5f5f5;
      font-family: Arial, sans-serif;
    }
    .container {
      max-width: 1200px;
      margin: 0 auto;
    }
    h1 {
      color: #2C3E50;
      text-align: center;
    }
    .instructions {
      background: white;
      padding: 20px;
      border-radius: 8px;
      margin-bottom: 30px;
      box-shadow: 0 2px 5px rgba(0,0,0,0.1);
    }
    .email-card {
      background: white;
      border-radius: 8px;
      margin-bottom: 30px;
      box-shadow: 0 2px 5px rgba(0,0,0,0.1);
      overflow: hidden;
    }
    .email-header {
      background: #2C3E50;
      color: white;
      padding: 15px 20px;
      display: flex;
      justify-content: space-between;
      align-items: center;
    }
    .email-header h2 {
      margin: 0;
      font-size: 18px;
    }
    .email-meta {
      font-size: 14px;
      opacity: 0.9;
    }
    .email-preview {
      padding: 20px;
      background: #fafafa;
    }
    .email-actions {
      padding: 15px 20px;
      background: #f0f0f0;
      display: flex;
      gap: 10px;
      align-items: center;
    }
    .btn {
      padding: 10px 20px;
      border-radius: 4px;
      text-decoration: none;
      font-size: 14px;
      cursor: pointer;
    }
    .btn-primary {
      background: #2C3E50;
      color: white;
    }
    .btn-success {
      background: #27ae60;
      color: white;
    }
    .btn-danger {
      background: #e74c3c;
      color: white;
    }
    .status-badge {
      padding: 5px 15px;
      border-radius: 20px;
      font-size: 12px;
      font-weight: bold;
    }
    .status-pending {
      background: #f39c12;
      color: white;
    }
    .status-approved {
      background: #27ae60;
      color: white;
    }
    .status-rejected {
      background: #e74c3c;
      color: white;
    }
    iframe {
      width: 100%;
      height: 500px;
      border: none;
      background: white;
    }
    .approval-form {
      padding: 20px;
      background: white;
    }
  </style>
</head>
<body>
  <div class="container">
    <h1>🏰 Cameron Estate Email Approval</h1>
    
    <div class="instructions">
      <h3>📋 Review Instructions</h3>
      <ol>
        <li>Click "View Preview" to see how each email renders</li>
        <li>Check that all images, links, and text appear correctly</li>
        <li>Press <strong>M</strong> in preview to toggle mobile view</li>
        <li>Click "Approve" when ready to push to GHL</li>
        <li>Click "Reject" to flag for changes</li>
      </ol>
      <p><strong>Images loaded:</strong> ${successResults.reduce((sum, r) => sum + (r.subject ? 1 : 0), 0)} emails with gallery images</p>
    </div>
    
    ${successResults.map((result, index) => `
    <div class="email-card" id="email-${index}">
      <div class="email-header">
        <div>
          <h2>${result.name}</h2>
          <div class="email-meta">Subject: ${result.subject}</div>
        </div>
        <span class="status-badge status-pending" id="status-${index}">Pending Review</span>
      </div>
      <div class="email-preview">
        <iframe src="${result.previewPath.split('/output/')[1]}" id="iframe-${index}"></iframe>
      </div>
      <div class="email-actions">
        <a href="${result.previewPath.split('/output/')[1]}" target="_blank" class="btn btn-primary">🔗 Open in New Tab</a>
        <button class="btn btn-success" onclick="approve(${index}, '${result.name}')">✓ Approve</button>
        <button class="btn btn-danger" onclick="reject(${index}, '${result.name}')">✗ Reject</button>
        <span style="margin-left: auto; font-size: 12px; color: #666;">
          Press M in preview for mobile view
        </span>
      </div>
      <div class="approval-form" id="form-${index}" style="display:none;">
        <label>Feedback:</label>
        <textarea id="feedback-${index}" style="width: 100%; height: 80px; margin-top: 10px; padding: 10px;"></textarea>
      </div>
    </div>
    `).join('')}
  </div>
  
  <script>
    function approve(index, name) {
      const status = document.getElementById('status-' + index);
      status.textContent = '✓ Approved';
      status.className = 'status-badge status-approved';
      alert('Email "' + name + '" approved! You can now push to GHL.');
    }
    
    function reject(index, name) {
      const form = document.getElementById('form-' + index);
      form.style.display = 'block';
      const status = document.getElementById('status-' + index);
      status.textContent = '✗ Rejected';
      status.className = 'status-badge status-rejected';
      alert('Email "' + name + '" flagged for changes. Please provide feedback.');
    }
    
    // Save approval state
    const approvals = {};
  </script>
</body>
</html>
  `;
  
  const approvalPath = path.join(__dirname, '../output/preview/approval.html');
  fs.writeFileSync(approvalPath, approvalHtml);
  
  return approvalPath;
}

/**
 * Main preview function
 */
async function main() {
  const program = new Command();
  
  program
    .name('email-preview')
    .description('Generate email previews for review')
    .option('--email <name>', 'Preview specific email (day1, day3)')
    .option('--all', 'Preview all emails');
  
  const options = program.parse();
  
  console.log('🏰 Cameron Estate Email Preview Generator');
  console.log('==========================================\n');
  
  // Determine which emails to preview
  const emailsToBuild = [];
  
  if (options.email) {
    // Check if the email key exists in the imported config
    const emailKey = Object.keys(emailConfigs).find(key => key.includes(options.email));
    if (emailKey) {
      emailsToBuild.push(emailKey);
    } else {
      console.error(`Email matching "${options.email}" not found.`);
    }
  } else {
    // Default: preview all
    emailsToBuild.push(...Object.keys(emailConfigs));
  }
  
  // Build each email
  const results = [];
  
  for (const emailId of emailsToBuild) {
    const result = await processEmail(emailId);
    if (result) {
      results.push(result);
    }
  }
  
  // Generate approval page
  const approvalPath = await generateApprovalPage(results);
  
  // Summary
  console.log('\n==========================================');
  console.log('📊 Preview Summary');
  console.log('==========================================');
  console.log(`Total emails: ${results.length}`);
  console.log(`Successful: ${results.filter(r => r.success).length}`);
  console.log(`Failed: ${results.filter(r => !r.success).length}`);
  
  console.log('\n📁 Output Files:');
  console.log(`   Approval Page: ${approvalPath}`);
  results.filter(r => r.success).forEach(r => {
    console.log(`   - ${r.name}: ${r.previewPath.split('/output/')[1]}`);
  });
  
  console.log('\n✨ Preview generation complete!');
  console.log(`\n📧 Open in browser: ${approvalPath}`);
  console.log('Press M in preview to toggle mobile view');
}

// Run if called directly
main().catch(console.error);

export { processEmail, generateApprovalPage, main };
