# Zeabur Deployment Configuration
# https://zeabur.com/docs

name: journey-visualizer
icon: https://cdn-icons-png.flaticon.com/512/2920/2920277.png

# Service configuration - Using Docker for custom build
services:
  - name: journey-visualizer
    type: docker
    build:
      dockerfile: Dockerfile
    ports:
      - port: 80
        protocol: http
    
# Build environment variables (set these in Zeabur dashboard)
# VITE_API_URL - API base URL (e.g., "https://journey-api.zeabur.app/api")
# VITE_DATA_SOURCE - Set to "api" for production

# Optional:
# VITE_GHL_API_KEY - GoHighLevel API key (if needed at build time)

# Health check
healthcheck:
  path: /health
  port: 80
